{% set min_python = "python >=3.8" %}
{% set version = "7.0.0" %}
{% set min_python = "python >=3.8" %}

# handle undefined PYTHON when rendering in `noarch:generic`
{% if PYTHON is undefined %}{% set PYTHON = "$PYTHON" %}{% endif %}

package:
  name: cyclonedx-python-lib
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cyclonedx-python-lib/cyclonedx_python_lib-{{ version }}.tar.gz
  sha256: 2519ca372285dcc856b0869f68af6daaa8868e91782117044f638bed5ea49dbd

build:
  noarch: python
  number: 0

requirements:
  host:
    - {{ min_python }}
  run:
    - {{ min_python }}

outputs:
  - name: cyclonedx-python-lib
    build:
      noarch: python
      script:
        - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
        # avoid regressing on https://github.com/CycloneDX/cyclonedx-python-lib/issues/435
        - |-
          {{ PYTHON }} -c "assert not (__import__('pathlib').Path(__import__('site').getsitepackages()[0]) / 'LICENSE').exists()"
    requirements:
      host:
        - {{ min_python }}
        - pip
        - poetry-core >=1.8.1
      run:
        - {{ min_python }}
        # from poetry-generated setup.py
        - license-expression >=30.0.0,<31.0.0
        - packageurl-python >=0.11,<2
        - py-serializable >=0.16.0,<2
        - sortedcontainers >=2.4.0,<3.0.0
    test: &simple_test
      imports:
        - cyclonedx
      commands:
        - pip check
      requires:
        - pip

  - name: cyclonedx-python-lib-with-json-validation
    build:
      noarch: generic
    requirements:
      host:
        - {{ min_python }}
      run:
        - {{ min_python }}
        - {{ pin_subpackage("cyclonedx-python-lib", exact=True) }}
        - jsonschema-with-format >=4.18,<5.0
    test: *simple_test

  - name: cyclonedx-python-lib-with-xml-validation
    build:
      noarch: generic
    requirements:
      host:
        - {{ min_python }}
      run:
        - {{ min_python }}
        - {{ pin_subpackage("cyclonedx-python-lib", exact=True) }}
        - lxml >=4,<6
    test: *simple_test

  - name: cyclonedx-python-lib-with-validation
    build:
      noarch: generic
    requirements:
      host:
        - {{ min_python }}
      run:
        - {{ min_python }}
        - {{ pin_subpackage("cyclonedx-python-lib", exact=True) }}
        - {{ pin_subpackage("cyclonedx-python-lib-with-json-validation", exact=True) }}
        - {{ pin_subpackage("cyclonedx-python-lib-with-xml-validation", exact=True) }}
    test:
      imports:
        - cyclonedx
      source_files:
        - tests
      commands:
        - pip check
        - pytest -vv --color=yes --tb=long --cov=cyclonedx --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=93
      requires:
        - ddt >=1.7.1,<2.0.0
        - pip
        - pytest-cov
        - tox
        - xmldiff

about:
  home: https://github.com/CycloneDX/cyclonedx-python-lib
  summary: Python library for CycloneDX
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  feedstock-name: cyclonedx-python-lib
  recipe-maintainers:
    - bollwyvl
