{% set version = "5.0.0" %}

package:
  name: cyclonedx-python-lib
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cyclonedx-python-lib/cyclonedx_python_lib-{{ version }}.tar.gz
  sha256: 46cdad7308a10cbad078e025ceb6ab9b27fa929d28cd7981f82a47653911b4aa

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    # TODO: restore after https://github.com/CycloneDX/cyclonedx-python-lib/issues/435
    # - |-
    #   {{ PYTHON }} -c "assert not (__import__('pathlib').Path(__import__('site').getsitepackages()[0]) / 'LICENSE').exists()"
    - |-
      {{ PYTHON }} -c "import os, pathlib; sp = pathlib.Path(os.environ['SP_DIR']); [(sp / f).unlink() for f in ['README.md', 'LICENSE', 'NOTICE']]"

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7
  run:
    - python >=3.7
    # from poetry-generated setup.py
    - license-expression >=30.0.0,<31.0.0
    - packageurl-python >=0.11
    - py-serializable >=0.11.1,<0.12.0
    - sortedcontainers >=2.4.0,<3.0.0

test:
  imports:
    - cyclonedx
  source_files:
    - tests
  commands:
    - pip check
    - pytest -vv --cov=cyclonedx --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=93
  requires:
    - ddt >=1.6.0,<2.0.0
    - jsonschema >=4.4.0
    - lxml >=4.7.0
    - pip
    - pytest-cov
    - tox
    - xmldiff

about:
  home: https://github.com/CycloneDX/cyclonedx-python-lib
  summary: A library for producing CycloneDX SBOM (Software Bill of Materials) files.
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - bollwyvl
