{% set version = "4.0.0" %}

package:
  name: cyclonedx-python-lib
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cyclonedx-python-lib/cyclonedx_python_lib-{{ version }}.tar.gz
  sha256: 4124dc111580fc026442525729febc956072788d1fc2b3300a54d27b5ff8b1b5

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps
    - |-
      {{ PYTHON }} -c "assert not (__import__('pathlib').Path(__import__('site').getsitepackages()[0]) / 'LICENSE').exists()"

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6
  run:
    - python >=3.6
    # from poetry-generated setup.py
    - packageurl-python >=0.9
    - setuptools >=47.0.0
    - sortedcontainers >=2.4.0,<3.0.0
    - toml >=0.10.0,<0.11.0
    # :python_version < "3.8"
    - importlib-metadata >=3.4

test:
  imports:
    - cyclonedx
  source_files:
    - tests
  commands:
    - pip check
    - pytest -vv --cov=cyclonedx --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=88
  requires:
    - ddt >=1.6.0,<2.0.0
    - jsonschema >=4.2.1
    - lxml >=4.7.0
    - pip
    - pytest-cov
    - tox
    - xmldiff

about:
  home: https://github.com/CycloneDX/cyclonedx-python-lib
  summary: A library for producing CycloneDX SBOM (Software Bill of Materials) files.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
