{% set version = "8.5.1" %}

{% set python_min = python_min | default("3.9") %}
{% set PYTHON = PYTHON | default("$PYTHON") %}

package:
  name: cyclonedx-python-lib
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/cyclonedx-python-lib/cyclonedx_python_lib-{{ version }}.tar.gz
  sha256: 2b419c6c5e422fd937aebebde4d3776c797b69c4eac80e515243dad8ebfcddcb

build:
  noarch: python
  number: 0

requirements:
  host:
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

outputs:
  - name: cyclonedx-python-lib
    build:
      noarch: python
      script:
        - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
        # avoid regressing on https://github.com/CycloneDX/cyclonedx-python-lib/issues/435
        - |-
          {{ PYTHON }} -c "assert not (__import__('pathlib').Path(__import__('site').getsitepackages()[0]) / 'LICENSE').exists()"
    requirements:
      host:
        - pip
        - poetry-core >=1.8.1
        - python {{ python_min }}
      run:
        # from poetry-generated setup.py
        - license-expression >=30.0.0,<31.0.0
        - packageurl-python >=0.11,<2
        - py-serializable >=1.1.1,<2
        - python >={{ python_min }}
        - sortedcontainers >=2.4.0,<3.0.0
    test: &simple_test
      imports:
        - cyclonedx
      commands:
        - pip check
      requires:
        - pip
        - python {{ python_min }}

  - name: cyclonedx-python-lib-with-json-validation
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("cyclonedx-python-lib", exact=True) }}
        - jsonschema-with-format >=4.18,<5.0
    test: *simple_test

  - name: cyclonedx-python-lib-with-xml-validation
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("cyclonedx-python-lib", exact=True) }}
        - lxml >=4,<6
    test: *simple_test

  - name: cyclonedx-python-lib-with-validation
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("cyclonedx-python-lib", exact=True) }}
        - {{ pin_subpackage("cyclonedx-python-lib-with-json-validation", exact=True) }}
        - {{ pin_subpackage("cyclonedx-python-lib-with-xml-validation", exact=True) }}
    test:
      imports:
        - cyclonedx
      source_files:
        - tests
        - pyproject.toml
      commands:
        - pip check
        - pytest -vv --color=yes --tb=long --cov=cyclonedx --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=90
      requires:
        - ddt >=1.7.1,<2.0.0
        - pip
        - pytest-cov
        - tox
        - xmldiff

about:
  home: https://github.com/CycloneDX/cyclonedx-python-lib
  summary: Python library for CycloneDX
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  feedstock-name: cyclonedx-python-lib
  recipe-maintainers:
    - bollwyvl
